### ISSUE TITLE
While the so file exist in the libs folder, couldn't find it when running the application

### ISSUE THREAD

**Issue by leverage2009lvt** [barteksc/PdfiumAndroid#54]
09-13 16:46:12.154 27548-27548/? E/com.shockwave.pdfium.PdfiumCore: Native libraries failed to load - java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.shockwave.pdfiumtest-2/base.apk"],nativeLibraryDirectories=[/data/app/com.shockwave.pdfiumtest-2/lib/arm64, /system/lib64, /vendor/lib64]]] couldn't find "libc++_shared.so"
09-13 16:46:12.160 27548-27548/? E/art: No implementation found for long com.shockwave.pdfium.PdfiumCore.nativeOpenDocument(int, java.lang.String) (tried Java_com_shockwave_pdfium_PdfiumCore_nativeOpenDocument and Java_com_shockwave_pdfium_PdfiumCore_nativeOpenDocument__ILjava_lang_String_2)
09-13 16:46:12.161 27548-27548/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.shockwave.pdfiumtest, PID: 27548
                                                   java.lang.UnsatisfiedLinkError: No implementation found for long com.shockwave.pdfium.PdfiumCore.nativeOpenDocument(int, java.lang.String) (tried Java_com_shockwave_pdfium_PdfiumCore_nativeOpenDocument and Java_com_shockwave_pdfium_PdfiumCore_nativeOpenDocument__ILjava_lang_String_2)
                                                       at com.shockwave.pdfium.PdfiumCore.nativeOpenDocument(Native Method)
                                                       at com.shockwave.pdfium.PdfiumCore.newDocument(PdfiumCore.java:135)
                                                       at com.shockwave.pdfium.PdfiumCore.newDocument(PdfiumCore.java:127)
                                                       at com.shockwave.pdfiumtest.PdfActivity.onCreate(PdfActivity.java:128)
                                                       at android.app.Activity.performCreate(Activity.java:6875)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2711)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2819)
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1558)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:163)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6396)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
09-13 16:46:12.595 476-2506/? E/ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only

**Comment by scarabdesign** [comment]
I'm getting this error when running an armeabi-v7a device, seems to work great on newer devices.

**Comment by windflowersnowandmoon** [comment]
> 09-13 16：46：12.154 27548-27548 /？E / com.shockwave.pdfium.PdfiumCore：本机库加载失败-java.lang.UnsatisfiedLinkError：dalvik.system.PathClassLoader [DexPathList [[zip file“ /data/app/com.shockwave.pdfiumtest-2/base.apk “]，nativeLibraryDirectories = [/数据/应用/ com.shockwave.pdfiumtest-2 / LIB / arm64，/系统/ lib64下，/供应商/ lib64下]]]找不到“的libc ++ _ shared.so” 
> 09-13 16：46：12.160 27548-27548 /？电子/艺术：找不到长com.shockwave.pdfium.PdfiumCore.nativeOpenDocument（int，java.lang.String）的实现（尝试Java_com_shockwave_pdfium_PdfiumCore_nativeOpenDocument和
> Java_com_shockwave_pdfium_PdfiumCore_nativeOpenDocument__ILjava_lang_String12 / 161-548：161吗？E / Android运行时：致命异常：主
> 进程：com.shockwave.pdfiumtest，PID：27548
> java.lang.UnsatisfiedLinkError：找不到长com.shockwave.pdfium.PdfiumCore.nativeOpenDocument（int，java.lang.String）的实现（尝试过Java_com_shockwave_pdfium_PdfiumCore_nativeOpenDocument和Java_com_shockwave_pdfium_PdfiumCore_nativeOpenDocument.IL 
> ）
> 。 com.shockwave.pdfium.com.shockwave.pdfium.PdfiumCore.newDocument（PdfiumCore.java:127）
> 上com.shockwave.pdfium.test.PdfActivity.onCreate（PdfActivity.java:128）
> 上的com.shockwave.pdfium.PdfiumCore.newDocument（PdfiumCore.java:135）
> 在android.app.Instrumentation.callActivityOnCreate 
> （Instrumentation.java:1119）的android.app.Activity.performCreate（Activity.java:6875 ）
> 在android.app.ActivityThread.performLaunchActivity（ActivityThread.java:2711）
> 在android.app.ActivityThread.handleLaunchActivity（ActivityThread.java:2819）
> 在android.app.ActivityThread.-wrap12（ActivityThread.java）
> 在android.app.ActivityThread $ H.handleMessage（ActivityThread.java:1558）
> 在android.os.Handler.dispatchMessage（Handler.java:102）
> 在android.os.Looper.loop（Looper.java:163）
> 在android.app.ActivityThread.main（ 位于com.android.internal.os.ZygoteInit $ MethodAndArgsCaller.run（ZygoteInit.java:904） 处的
> java.lang.reflect.Method.invoke（本机方法）
> 处的ActivityThread.java:6396）
> ZygoteInit.main（ZygoteInit.java:794）
> 09-13 16：46：12.595 476-2506 /？E / ANDR-PERF-MPCTL：无效的配置文件编号。0，总共0个配置文件

这个问题解决了吗？？我这里是缺少so文件，jnipdfium.so

**Comment by liaoxuanwei** [comment]
我用Eclipse使用最新Master Pdfium库也报错
01-01 09:03:04.339: W/dalvikvm(7351): No implementation found for native Lcom/shockwave/pdfium/PdfiumCore;.nativeOpenDocument:(ILjava/lang/String;)J
01-01 09:03:04.341: E/PDFView(7351): load pdf error
01-01 09:03:04.341: E/PDFView(7351): java.lang.UnsatisfiedLinkError: Native method not found: com.shockwave.pdfium.PdfiumCore.nativeOpenDocument:(ILjava/lang/String;)J
01-01 09:03:04.341: E/PDFView(7351): 	at com.shockwave.pdfium.PdfiumCore.nativeOpenDocument(Native Method)

怎么解决
